# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9297b5810739ab2595c8c30fe03644ff08fd71b41e6c0dcd7e4994cb089dc602dc9142c9fe80611dcd0599d6da9e2fc45c67a284ea245f9f0afa347114dfb02

test:
  secret_key_base: 5d3ee9ab09eb307cb7949a006cc44b396b38644881afbeaad19ef900f0143c0a8634d2eca288eb168d148fb29806f14f809d2583ca6ed6e44f7a92113481972c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
